### ISSUE TITLE
Get specific image

### ISSUE THREAD

**Issue by oyeanuj** [marciobarrios/react-unsplash-wrapper#2]
Hi @marciobarrios, thanks for creating this library! Is there support for displaying a specific image by id?

**Comment by marciobarrios** [comment]
Hi @oyeanuj, not yet but I can easily add support for image id, give me a couple of days.

**Comment by oyeanuj** [comment]
@marciobarrios Thank you, looking forward to it!

**Comment by marciobarrios** [comment]
@oyeanuj you already have the possibility to show a specific image:
```jsx
<Unsplash photoId="WLUHO9A_xik" />
```

The code is already in master and the NPM version is already updated (1.1.3), I also updated the README and added a link to a CodeSandbox with lots of examples: https://codesandbox.io/s/5wx6j02034

**Comment by marciobarrios** [comment]
I'm closing this issue, I hope it worked! :)
